apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: istio-ingressgateway-secure
  name: istio-ingressgateway-secure
  namespace: istio-system
spec:
  host: gateway.istio.showcase.literalice.com
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  wildcardPolicy: Subdomain
