apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: devops-ex-line-gateway
  name: devops-ex-line-gateway

---

kind: "BuildConfig"
apiVersion: "v1"
metadata:
  labels:
    app: devops-ex-line-gateway
  name: "devops-ex-line-gateway"
spec:
  runPolicy: "Serial"
  triggers: 
    - type: "ImageChange"
  source: 
    git:
      uri: "https://github.com/literalice/devops-ex.git"
    contextDir: "line-gateway" 
  strategy: 
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "redhat-openjdk18-openshift:1.4"
        namespace: "openshift"
  output:
    to:
      kind: "ImageStreamTag"
      name: "devops-ex-line-gateway:latest"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devops-ex-line-gateway
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: devops-ex-line-gateway
        version: v1
    spec:
      containers:
      - name: app
        image: docker-registry.default.svc:5000/showcase-istio/devops-ex-line-gateway
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devops-ex-line-gateway
  labels:
    app: devops-ex-line-gateway
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: devops-ex-line-gateway
